apiVersion: v1
kind: Namespace
metadata:
  name: qualys-system
  labels:
    app.kubernetes.io/name: qualys-k8s-scanner
    app.kubernetes.io/component: security-scanner
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qualys-scanner
  namespace: qualys-system
  labels:
    app.kubernetes.io/name: qualys-k8s-scanner
    app.kubernetes.io/component: security-scanner
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qualys-k8s-scanner
  labels:
    app.kubernetes.io/name: qualys-k8s-scanner
    app.kubernetes.io/component: security-scanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qualys-k8s-scanner
subjects:
  - kind: ServiceAccount
    name: qualys-scanner
    namespace: qualys-system
